#!/bin/sh
# This is a general script to start the decorations (eg, tray, conky, etc)
# for a specified desktop environment / window manager. This script should
# detect the computer (desktop vs laptop) it is on and choose the settings
# accordingly.

# Usage: <desktop environment name> <start | stop| restart>

# Decision logic:
# 1) Which desktop environment?
#     2) What action are we performing?
#         3) If relevant: What host are we on?

if [ $# -ne 2 ]; then
	echo "Usage: $0 <i3> <start | stop | restart>" >&2
	exit 1
fi

case "$1" in
i3)
	case "$2" in
	start)
		rotate-wallpaper.sh

		#trayer --edge bottom --align right --SetDockType true --transparent true --alpha 0 --tint 000000 &
		#For transparency: trayer --edge bottom --align right --SetDockType true --transparent true --alpha 255
		
		case "$HOSTNAME" in
		beacon)
			CONKY_CONFIG=conky.i3.beacon.workspace
			DZEN_WIDTH=840
			DZEN_HEIGHT=18
			DZEN_X=$(( (1920 - $DZEN_WIDTH) / 2 ))
			DZEN_Y=$(( 1080 - $DZEN_HEIGHT ))
			;;
		esac
	
		# Note that dzen exits on button 3 by default.
		# Use button3 to hide it, and hovering over it to restore it.
		exec conky -c ~/.config/conky/$CONKY_CONFIG | \
		     dzen2 -x $DZEN_X -y $DZEN_Y -h $DZEN_HEIGHT -w $DZEN_WIDTH -ta c -p -bg "#000000" -fg "#ffffff" \
		           -e 'onstart=raise;button3=togglehide;entertitle=unhide' \
		           -fn "-adobe-helvetica-medium-r-normal-*-11-80-100-*-*-*-iso8859-*" &
		;;
	stop)
		killall conky 2> /dev/null
		killall dzen2 2> /dev/null
		;;
	restart)
		"$0" "$1" stop
		"$0" "$1" start
		;;
	esac
	;;
esac

