#!/bin/sh

if [ -z `which youtube-dl` -o -z `which ffmpeg` -o -z `which ffprobe` ]; then
	echo "Error: Could not find youtube-dl, ffmpeg, or ffprobe" >&2
	exit 1
fi

if [ -z "$1" ]; then
	echo "Error: Please specify an output filename" >&2
	exit 1
fi

if [ -z "$2" ]; then
	echo "Error: Argument 1 must be YouTube link" >&2
	exit 1
fi

youtube-dl -o $1 --extract-audio --audio-format=mp3 $2

